travis:
  secure:
    BINSTAR_TOKEN: E5RQpfgJN+Xr2zHQh3ULmvpXQBnPEExGaCpXIBiFxKXL0K1IPCcbV7fqq22kcScTBqvRg4Tpnhe94tjCIaUyXncHcylE2fvGwvQL77mLSkWT6Q4WbxATSbf/wRl1XJNoXl57ml5ndCPNJmUT9Lu75VmS5AxrCSzvBSGEKoCvYjOE25AJrTcZ3yYwPaFqc+gnUWWUXw/24yydHp5SUO2xmTxGJHF0y2nQJpCGrs6amMcvXKpb6z2gFjdwNCBClGhvI5NV1Y3Mrl0l6dHlc2ur6SnW020pjscIbay8rgw84Jax8rPvYDwU/6+9+0FGwamR7I/H/ECLlvgRSLo/HwnGD+J8RMB8cxmxEP3MCBISmxuwezgDs0jn6/Q9eqqsoExgkkXhf78LKDBjLc8qRx6KZ/tFwdcXY+BzCl0LdYQkSw+TWNXyWZE8hNC3v/S6eEH7kua331WpdOuuZxHuSgDdBXAHGiEdrfi5q2BChYNcp7Xx1kDy1Dwg05Mhbqw0Lrj2Ug3hBFA9rX7zi+/+T/nkv4hfNoVKbyC4uIXf7ka2LQU21Iu18iE6nDmWiwez39IkeXOYYu0oozGaR5jtIveWwLUJFgrwX+sy1TV+tNnZdbTzSSxqLKGBk6wF4/+FmoTnKnUnzfKBUBm7fm/reJ9qiKyNIqiSdWEwK+QW8J5iIDM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
