appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dbKU3DjTZokR2NOV6WcyBRjUtPYl093rCJRakByumeVVY242fbSWslxN8Xb3OB7OmHolfopoTNYIHRXHHmRmfZHPJgkxzR8cU9gJ16krqWb3/EDiCft5uIOW2mkzhQ2TvY9tuh/OFKOsa+SuH9KGnzFjie8Zx+DOhicGkY1hJyWfrtKdUCxBpKQb2SjZYRC4EVc8nCwLLevH8f1ZxhuIBh1orsj4a5C4KTtzwAPJ+mN3SkapK+YNLUh43G2CHXPllbyzH0P0B4BlbxNRJ1wOqocRHgxBvLsTN7ckgWuvtnQOrVOJ17ZxdgOlbQBn9QmT+dN5REsdZ2hdpQaGOF2L5w1FvrqreXNUSMBmnREo4hCC1lK3b/yXWgS/KoBNpbT/n6VPoMQItXlE2W/+iqI9hrGiO5lGBgnNc5ycJT/lPMF4C3InoBmnGBCtjttZmq/goVAlFbZfURJnAhic8IYM2lQhQ0bJ1vMlI51Gvr+fCdaOCT0n0AzD/eGrMQBLtAeLh6No9IcJL5yHuJtpFzCUVL0wB+BUQPTkQfx9x1ADdWsxQi2Avybv+uFjxX0xtDHxZd9LiS/GQ829c5tw9poY4PebLqJMpVSfdl0sMNAHXT0nXOedC8P1GVInBygCJL42MS7kWRxpQrp0EF4T7fSjIAYfFy38YTMX1xqZXu0Swzg=}
